### ISSUE TITLE
"up"lama

### ISSUE THREAD

**Issue by babua** [fetfrip/fetfrip#1]
"sorting" seceneklerinden "last updated" calismiyor. ff'teki gibi en son aktiviteye gore dizilim yapmali.

**Comment by ufukk** [comment]
https://github.com/humhub/humhub/issues/555

**Comment by ufukk** [comment]
Ben de last updated seçeneğini çalıştıramadım. Çalışsa bile, public feedler değil "my spaces" altındaki feedler için geçerli olacak.
