### ISSUE TITLE
real-time updates + reordering

### ISSUE THREAD

**Issue by babua** [fetfrip/fetfrip#3]
su an ff'teki gibi gercek zamanli guncelleme yok. post'larin yeniden siraya koyulmasi ikinci planda, ama comment'lerin eklendiginin gercek zamanli gorulmesi muhabbetin/tartismanin gidisati icin onemli olabiliyor. comment update'ler birinci oncelik.

**Comment by ufukk** [comment]
Mevcut sürüm feedleri oluşturulma tarihine göre diziyor. Aldıkları yorum ve like'lara göre yukarı çıkarmıyor.

**Comment by babua** [comment]
[humhub#229](https://github.com/humhub/humhub/issues/229)

**Comment by fsniper** [comment]
websocketleri kurcalıyorum. bakalım bakalım.
