### ISSUE TITLE
Feed alanına url yapıştırıldığında, url'in kendisi yerine başlık + özet + görsel'den oluşan şablon üretmesi. 

### ISSUE THREAD

**Issue by ufukk** [fetfrip/fetfrip#8]
Facebook durum güncelleme kutularındaki işleve benzer. Belki facebook'un meta tagleri bile kullanılabilir.

**Comment by ufukk** [comment]
https://github.com/humhub/humhub/issues/752

**Comment by fsniper** [comment]
https://github.com/samet/humhub/pull/21 Şöyle bişey yaptım

**Comment by samet** [comment]
Embedly cards kullaniyoruz artik, bu issue'yu kapatiyorum.
